# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
lane :run_unit_tests do
    scan(
    scheme: "USMovies", # Replace with your actual test scheme
    clean: true, # Clean the build before running tests
    output_directory: "fastlane/test_output", # Store test results here
    output_types: "junit,json", # Generate JUnit & JSON test reports
    fail_build: true # Fail if tests fail
  )
  end

end
