name: iOS CI - Build- App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup runner
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: 16.1
          
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      
      - uses: actions/cache@v3
        id: Cache-spm
        with: 
         path: spm-cache
         key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
         restore-keys: |
            ${{ runner.os }}-spm-

      - name: build app
        run: |
          
          bundle exec fastlane run_unit_tests